FROM eclipse-temurin:21-jre-alpine

LABEL maintainer="jalena@bcsytv.com"

RUN apk add --no-cache tzdata fontconfig ttf-dejavu ca-certificates && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    fc-cache -f -v && \
    rm -rf /var/cache/apk/*

COPY ./font /usr/share/fonts/win/